import * as stylex from '@stylexjs/stylex';

const suggestion_flyout_in = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(4px) scale(0.98)' },
  to: { opacity: 1, transform: 'translateY(0) scale(1)' },
});

const styles = stylex.create({
  page: {
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minHeight: 0,
    flexDirection: "column",
    gap: "12px",
  },
  page_drawer: {
    width: '100%',
    height: '100%',
    minHeight: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
    gap: 0,
  },
  page_header: {
    display: "flex",
    alignItems: {
      default: "center",
      "@media (max-width: 640px)": "flex-start",
    },
    justifyContent: "space-between",
    gap: "16px",
    flexShrink: 0,
  },
  identity: {
    display: "flex",
    alignItems: "center",
    gap: "11px",
    minWidth: 0,
  },
  identity_name: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    maxWidth: "min(520px, 60vw)",
    marginTop: "2px",
    overflow: "hidden",
    color: "var(--muted)",
    fontSize: "0.84rem",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  avatar: {
    width: "44px",
    height: "44px",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "44px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "50%",
    backgroundColor: "var(--card-soft)",
    color: "var(--brand)",
    objectFit: "cover",
  },
  avatar__small: {
    width: "30px",
    height: "30px",
    flexBasis: "30px",
  },
  avatar__fallback: {
    backgroundColor: "color-mix(in srgb, var(--brand) 10%, var(--card))",
  },
  shell: {
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minHeight: 0,
    minWidth: 0,
    flexDirection: "column",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius)",
    backgroundColor: "var(--card)",
    boxShadow: "var(--shadow)",
  },
  shell_drawer: {
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: 0,
    boxShadow: 'none',
  },
  scroll: {
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minHeight: 0,
    flexDirection: "column",
    gap: "12px",
    overflowY: "auto",
    paddingTop: {
      default: "18px",
      "@media (max-width: 640px)": "13px",
    },
    paddingRight: {
      default: "18px",
      "@media (max-width: 640px)": "13px",
    },
    paddingBottom: {
      default: "18px",
      "@media (max-width: 640px)": "13px",
    },
    paddingLeft: {
      default: "18px",
      "@media (max-width: 640px)": "13px",
    },
    overscrollBehavior: "contain",
  },
  message_row: {
    display: "flex",
    width: "100%",
    alignItems: "flex-end",
    gap: "8px",
  },
  message_row_user: {
    justifyContent: "flex-end",
  },
  msg: {
    maxWidth: {
      default: "78%",
      "@media (max-width: 640px)": "88%",
    },
    minWidth: 0,
    paddingTop: "10px",
    paddingRight: "13px",
    paddingBottom: "10px",
    paddingLeft: "13px",
    overflowWrap: "anywhere",
    borderRadius: "14px",
    lineHeight: 1.45,
  },
  msg_user: {
    borderBottomRightRadius: "4px",
    backgroundColor: "var(--brand)",
    color: "var(--brand-text)",
    whiteSpace: "pre-wrap",
  },
  msg_agent: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderBottomLeftRadius: "4px",
    backgroundColor: "var(--card-soft)",
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  message_text: {
    whiteSpace: "pre-wrap",
  },
  greeting: {
    whiteSpace: "pre-wrap",
    color: "var(--muted)",
  },
  sender: {
    position: "absolute",
    width: "1px",
    height: "1px",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
    borderStyle: "none",
  },
  result: {
    display: "flex",
    alignItems: "flex-start",
    gap: "7px",
    paddingTop: "8px",
    paddingRight: "10px",
    paddingBottom: "8px",
    paddingLeft: "10px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderRadius: "8px",
    fontSize: "0.9rem",
  },
  result_ok: {
    borderColor: "color-mix(in srgb, var(--success) 65%, var(--border))",
    backgroundColor: "color-mix(in srgb, var(--success) 7%, transparent)",
  },
  result_failed: {
    borderColor: "color-mix(in srgb, var(--alert-error) 70%, var(--border))",
    backgroundColor: "color-mix(in srgb, var(--alert-error) 7%, transparent)",
  },
  card_list: {
    display: "grid",
    gap: "8px",
  },
  data_card: {
    display: "flex",
    minWidth: 0,
    alignItems: {
      default: "center",
      "@media (max-width: 640px)": "flex-start",
    },
    gap: "10px",
    paddingTop: "11px",
    paddingRight: "11px",
    paddingBottom: "11px",
    paddingLeft: "11px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "9px",
    backgroundColor: "var(--bg-elev)",
  },
  data_card_icon: {
    width: "34px",
    height: "34px",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "34px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: "var(--pill-bg)",
    color: "var(--brand)",
  },
  transaction_direction: {
    width: "34px",
    height: "34px",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "34px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: "var(--pill-bg)",
    color: "var(--brand)",
  },
  data_card_main: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minWidth: 0,
  },
  data_card_heading: {
    display: "flex",
    minWidth: 0,
    alignItems: {
      default: "baseline",
      "@media (max-width: 640px)": "flex-start",
    },
    justifyContent: "space-between",
    gap: "12px",
  },
  data_card_note: {
    marginTop: "2px",
    color: "var(--muted)",
    fontSize: "0.84rem",
    overflowWrap: "anywhere",
  },
  data_card_meta: {
    display: "flex",
    minWidth: 0,
    flexWrap: "wrap",
    alignItems: {
      default: "center",
      "@media (max-width: 640px)": "flex-start",
    },
    rowGap: {
      default: "4px",
      "@media (max-width: 640px)": "2px",
    },
    columnGap: {
      default: "10px",
      "@media (max-width: 640px)": "2px",
    },
    marginTop: "5px",
    color: "var(--muted)",
    fontSize: "0.74rem",
    flexDirection: {
      default: null,
      "@media (max-width: 640px)": "column",
    },
  },
  meta_label: {
    marginRight: "2px",
    color: "var(--fg)",
    fontSize: "0.92em",
    fontWeight: 600,
  },
  card_actions: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    gap: "5px",
  },
  card_status: {
    display: "inline-flex",
    flexShrink: 0,
    paddingTop: "2px",
    paddingRight: "7px",
    paddingBottom: "2px",
    paddingLeft: "7px",
    borderRadius: "999px",
    backgroundColor: "var(--pill-bg)",
    color: "var(--muted)",
    fontSize: "0.65rem",
    fontWeight: 650,
    letterSpacing: "0.04em",
    lineHeight: 1.45,
    textTransform: "uppercase",
  },
  step_status: {
    display: "inline-flex",
    flexShrink: 0,
    paddingTop: "2px",
    paddingRight: "7px",
    paddingBottom: "2px",
    paddingLeft: "7px",
    borderRadius: "999px",
    backgroundColor: "var(--pill-bg)",
    color: "var(--muted)",
    fontSize: "0.65rem",
    fontWeight: 650,
    letterSpacing: "0.04em",
    lineHeight: 1.45,
    textTransform: "uppercase",
  },
  card_status_status_active: {
    backgroundColor: "color-mix(in srgb, var(--success) 14%, transparent)",
    color: "var(--success)",
  },
  card_status_status_completed: {
    backgroundColor: "color-mix(in srgb, var(--success) 14%, transparent)",
    color: "var(--success)",
  },
  card_status_status_complete: {
    backgroundColor: "color-mix(in srgb, var(--success) 14%, transparent)",
    color: "var(--success)",
  },
  card_status_status_paid: {
    backgroundColor: "color-mix(in srgb, var(--success) 14%, transparent)",
    color: "var(--success)",
  },
  card_status_status_success: {
    backgroundColor: "color-mix(in srgb, var(--success) 14%, transparent)",
    color: "var(--success)",
  },
  step_status_status_done: {
    backgroundColor: "color-mix(in srgb, var(--success) 14%, transparent)",
    color: "var(--success)",
  },
  step_status_status_completed: {
    backgroundColor: "color-mix(in srgb, var(--success) 14%, transparent)",
    color: "var(--success)",
  },
  card_status_status_pending: {
    backgroundColor: "color-mix(in srgb, var(--alert-info) 14%, transparent)",
    color: "var(--alert-info)",
  },
  step_status_status_ready: {
    backgroundColor: "color-mix(in srgb, var(--alert-info) 14%, transparent)",
    color: "var(--alert-info)",
  },
  step_status_status_pending: {
    backgroundColor: "color-mix(in srgb, var(--alert-info) 14%, transparent)",
    color: "var(--alert-info)",
  },
  card_status_status_failed: {
    backgroundColor: "color-mix(in srgb, var(--alert-error) 12%, transparent)",
    color: "var(--alert-error)",
  },
  card_status_status_cancelled: {
    backgroundColor: "color-mix(in srgb, var(--alert-error) 12%, transparent)",
    color: "var(--alert-error)",
  },
  card_status_status_declined: {
    backgroundColor: "color-mix(in srgb, var(--alert-error) 12%, transparent)",
    color: "var(--alert-error)",
  },
  card_status_status_expired: {
    backgroundColor: "color-mix(in srgb, var(--alert-error) 12%, transparent)",
    color: "var(--alert-error)",
  },
  step_status_status_failed: {
    backgroundColor: "color-mix(in srgb, var(--alert-error) 12%, transparent)",
    color: "var(--alert-error)",
  },
  transaction_direction_sent: {
    color: "var(--alert-error)",
  },
  transaction_direction_received: {
    color: "var(--success)",
  },
  transaction_party: {
    color: {
      default: "var(--brand)",
      ":hover": "var(--brand-dark)",
    },
    fontWeight: 700,
    textDecoration: {
      default: "none",
      ":hover": "underline",
    },
    textUnderlineOffset: {
      default: null,
      ":hover": "2px",
    },
  },
  amount_sent: {
    color: "var(--alert-error)",
    whiteSpace: "nowrap",
  },
  amount_received: {
    color: "var(--success)",
    whiteSpace: "nowrap",
  },
  weather_icon: {
    width: "54px",
    height: "54px",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "54px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "2.5rem",
    lineHeight: 1,
    overflow: "hidden",
    whiteSpace: "nowrap",
  },
  weather_response: {
    display: "grid",
    gap: "10px",
  },
  weather_summary: {
    color: "var(--fg)",
    lineHeight: 1.5,
  },
  weather_card: {
    display: "block",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    overflow: "hidden",
  },
  weather_current: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    paddingTop: "14px",
    paddingRight: "16px",
    paddingBottom: "12px",
    paddingLeft: "16px",
  },
  weather_temperature: {
    display: "block",
    color: "var(--fg)",
    fontSize: "1.9rem",
    lineHeight: 1.1,
    whiteSpace: "nowrap",
  },
  weather_label: {
    marginTop: "3px",
    color: "var(--muted)",
    fontSize: "0.82rem",
  },
  weather_details: {
    display: "flex",
    flexWrap: "wrap",
    rowGap: "8px",
    columnGap: "18px",
    paddingTop: "8px",
    paddingRight: "16px",
    paddingBottom: "8px",
    paddingLeft: "16px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    color: "var(--muted)",
    fontSize: "0.78rem",
  },
  weather_forecast: {
    display: "flex",
    overflowX: "auto",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    overscrollBehaviorX: "contain",
  },
  weather_day: {
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: "96px",
    minWidth: 0,
    paddingTop: "9px",
    paddingRight: "7px",
    paddingBottom: "10px",
    paddingLeft: "7px",
    textAlign: "center",
  },
  weather_day_name: {
    color: "var(--muted)",
    fontSize: "0.72rem",
  },
  weather_day_icon: {
    height: "29px",
    marginTop: "3px",
    marginRight: 0,
    marginBottom: "3px",
    marginLeft: 0,
    fontSize: "1.3rem",
    lineHeight: "29px",
    whiteSpace: "nowrap",
  },
  weather_day_temperatures: {
    color: "var(--fg)",
    fontSize: "0.76rem",
    whiteSpace: "nowrap",
  },
  weather_day_label: {
    marginTop: "2px",
    overflow: "hidden",
    color: "var(--muted)",
    fontSize: "0.66rem",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  step_list: {
    display: "grid",
    gap: "8px",
  },
  step: {
    paddingTop: "10px",
    paddingRight: "10px",
    paddingBottom: "10px",
    paddingLeft: "10px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "8px",
    backgroundColor: "var(--bg-elev)",
  },
  step_head: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "12px",
  },
  step_description: {
    marginTop: "3px",
    fontSize: "0.88rem",
  },
  step_note: {
    marginTop: "5px",
    color: "var(--muted)",
    fontSize: "0.78rem",
  },
  confirm_actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
  confirm_state: {
    marginTop: "8px",
    color: "var(--muted)",
    fontSize: "0.76rem",
  },
  thinking: {
    display: "flex",
    alignSelf: "flex-start",
    alignItems: "center",
    gap: "8px",
    paddingTop: "3px",
    paddingRight: "4px",
    paddingBottom: "3px",
    paddingLeft: "38px",
    color: "var(--muted)",
    fontSize: "0.84rem",
  },
  empty: {
    display: "flex",
    width: "min(520px, 100%)",
    marginTop: "auto",
    marginRight: "auto",
    marginBottom: "auto",
    marginLeft: "auto",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: "24px",
    paddingRight: "12px",
    paddingBottom: "24px",
    paddingLeft: "12px",
    textAlign: "center",
  },
  suggestions: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "8px",
    marginTop: "18px",
  },
  suggestion: {
    paddingTop: "7px",
    paddingRight: "12px",
    paddingBottom: "7px",
    paddingLeft: "12px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: "var(--border)",
      ":hover": "var(--brand)",
    },
    borderRadius: "999px",
    backgroundColor: {
      default: "var(--pill-bg)",
      ":hover": "color-mix(in srgb, var(--brand) 7%, var(--pill-bg))",
    },
    color: {
      default: "var(--fg)",
      ":hover": "var(--fg)",
    },
    fontSize: "0.8rem",
    fontWeight: 450,
    textAlign: "left",
    minHeight: {
      default: null,
      "@media (pointer: coarse)": "44px",
    },
  },
  loading: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    paddingTop: "4px",
    paddingRight: "4px",
    paddingBottom: "4px",
    paddingLeft: "4px",
  },
  skeleton_row: {
    display: "flex",
    alignItems: "flex-end",
    gap: "8px",
  },
  skeleton_row_user: {
    justifyContent: "flex-end",
  },
  load_error: {
    display: "flex",
    width: "min(560px, 100%)",
    marginTop: "auto",
    marginRight: "auto",
    marginBottom: "auto",
    marginLeft: "auto",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
  },
  composer: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    alignItems: "flex-end",
    gap: "8px",
    paddingTop: {
      default: "10px",
      "@media (max-width: 640px)": "8px",
    },
    paddingRight: {
      default: "10px",
      "@media (max-width: 640px)": "8px",
    },
    paddingBottom: {
      default: "10px",
      "@media (max-width: 640px)": "8px",
    },
    paddingLeft: {
      default: "10px",
      "@media (max-width: 640px)": "8px",
    },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    backgroundColor: "var(--bg-elev)",
    flexShrink: 0,
  },
  composer_input: {
    position: "relative",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minWidth: 0,
  },
  character_count: {
    position: "absolute",
    right: "10px",
    bottom: "11px",
    color: "var(--muted)",
    fontSize: "0.68rem",
    fontVariantNumeric: "tabular-nums",
    pointerEvents: "none",
  },
  character_count_near_limit: {
    color: "var(--alert-warning)",
  },
  suggestion_menu: {
    position: "absolute",
    right: "7px",
    bottom: "7px",
    zIndex: 3,
  },
  suggestion_trigger: {
    width: "30px",
    height: "30px",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  suggestion_flyout: {
    position: "absolute",
    right: 0,
    bottom: "calc(100% + 8px)",
    zIndex: 4,
    width: "min(280px, calc(100vw - 32px))",
    maxHeight: "min(300px, 45dvh)",
    paddingTop: "6px",
    paddingRight: "6px",
    paddingBottom: "6px",
    paddingLeft: "6px",
    overflowY: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "11px",
    backgroundColor: "var(--card)",
    boxShadow: "var(--shadow)",
    transformOrigin: "bottom right",
    animationName: suggestion_flyout_in,
    animationDuration: '100ms',
    animationTimingFunction: 'ease-out',
    animationFillMode: 'forwards',
  },
  suggestion_option: {
    width: "100%",
    minHeight: {
      default: "38px",
      "@media (pointer: coarse)": "44px",
    },
    paddingTop: "8px",
    paddingRight: "10px",
    paddingBottom: "8px",
    paddingLeft: "10px",
    justifyContent: "flex-start",
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "7px",
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in srgb, var(--brand) 9%, var(--pill-bg))",
      ":focus-visible": "color-mix(in srgb, var(--brand) 9%, var(--pill-bg))",
    },
    color: {
      default: "var(--fg)",
      ":hover": "var(--fg)",
      ":focus-visible": "var(--fg)",
    },
    fontSize: "0.8rem",
    fontWeight: 450,
    lineHeight: 1.35,
    textAlign: "left",
  },
  message_pending: {
    opacity: 0.78,
  },
  payment_card: {
    flexWrap: {
      default: null,
      "@media (max-width: 640px)": "wrap",
    },
  },
  layout_container: {
    minHeight: 0,
    overflow: 'hidden',
  },
  identity_heading: {
    margin: 0,
    lineHeight: 1.15,
  },
  identity_spinner: {
    width: 12,
    height: 12,
    borderWidth: 2,
  },
  user_link: {
    color: 'inherit',
    textDecoration: 'underline',
  },
  msg_agent_card: {
    width: {
      default: 'min(700px, calc(100% - 38px))',
      '@media (max-width: 640px)': 'calc(100% - 38px)',
    },
    maxWidth: {
      default: 'min(700px, calc(100% - 38px))',
      '@media (max-width: 640px)': 'calc(100% - 38px)',
    },
  },
  msg_agent_weather: {
    width: {
      default: 'min(900px, calc(100% - 38px))',
      '@media (max-width: 640px)': 'calc(100% - 38px)',
    },
    maxWidth: {
      default: 'min(900px, calc(100% - 38px))',
      '@media (max-width: 640px)': 'calc(100% - 38px)',
    },
  },
  result_icon: {
    flexShrink: 0,
    marginTop: 2,
  },
  result_icon_ok: {
    color: 'var(--success)',
  },
  result_icon_failed: {
    color: 'var(--alert-error)',
  },
  payment_heading: {
    justifyContent: 'flex-start',
    gap: 8,
  },
  heading_child: {
    minWidth: 0,
  },
  meta_mono: {
    maxWidth: {
      default: 220,
      '@media (max-width: 640px)': '100%',
    },
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  card_action: {
    minHeight: {
      default: 32,
      '@media (pointer: coarse)': 44,
    },
    paddingTop: 5,
    paddingRight: 8,
    paddingBottom: 5,
    paddingLeft: 8,
  },
  card_action_button: {
    minWidth: {
      default: null,
      '@media (pointer: coarse)': 44,
    },
  },
  weather_detail: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
  },
  weather_day_after: {
    borderLeftWidth: 1,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--border)',
  },
  thinking_spinner: {
    width: 13,
    height: 13,
    borderWidth: 2,
  },
  empty_avatar: {
    width: 64,
    height: 64,
    flexBasis: 64,
  },
  empty_heading: {
    marginTop: 12,
    marginRight: 0,
    marginBottom: 5,
    marginLeft: 0,
  },
  load_error_alert: {
    width: '100%',
  },
  composer_textarea: {
    display: 'block',
    minHeight: 44,
    maxHeight: 140,
    resize: 'none',
    paddingTop: 10,
    paddingRight: 58,
    paddingBottom: 10,
    paddingLeft: 13,
    overflowY: 'auto',
    lineHeight: 1.4,
  },
  composer_textarea_with_menu: {
    paddingRight: 94,
  },
  character_count_with_menu: {
    right: 44,
  },
  submit_button: {
    height: 44,
    flexShrink: 0,
    paddingRight: {
      default: null,
      '@media (max-width: 640px)': 13,
    },
    paddingLeft: {
      default: null,
      '@media (max-width: 640px)': 13,
    },
  },
  submit_spinner: {
    width: 13,
    height: 13,
    borderWidth: 2,
    borderColor: 'color-mix(in srgb, currentColor 25%, transparent)',
    borderTopColor: 'currentColor',
    borderRightColor: 'currentColor',
  },
  reset_button: {
    marginTop: {
      default: null,
      '@media (max-width: 640px)': 3,
    },
  },
  payment_card_actions: {
    width: {
      default: null,
      '@media (max-width: 640px)': '100%',
    },
    justifyContent: {
      default: null,
      '@media (max-width: 640px)': 'flex-end',
    },
    paddingLeft: {
      default: null,
      '@media (max-width: 640px)': 44,
    },
  },
  confirm_action_button: {
    minHeight: {
      default: null,
      '@media (pointer: coarse)': 44,
    },
  },
});

export const agent_classes = {
  page: stylex.props(styles.page).className,
  page_drawer: stylex.props(styles.page, styles.page_drawer).className,
  page_header: stylex.props(styles.page_header).className,
  identity: stylex.props(styles.identity).className,
  identity_name: stylex.props(styles.identity_name).className,
  avatar: stylex.props(styles.avatar).className,
  avatar__small: stylex.props(styles.avatar, styles.avatar__small).className,
  avatar__fallback: stylex.props(styles.avatar, styles.avatar__fallback).className,
  avatar_fallback_small: stylex.props(styles.avatar, styles.avatar__fallback, styles.avatar__small).className,
  avatar_fallback_large: stylex.props(styles.avatar, styles.avatar__fallback, styles.empty_avatar).className,
  shell: stylex.props(styles.shell).className,
  shell_drawer: stylex.props(styles.shell, styles.shell_drawer).className,
  scroll: stylex.props(styles.scroll).className,
  message_row: stylex.props(styles.message_row).className,
  message_row_user: stylex.props(styles.message_row_user).className,
  msg: stylex.props(styles.msg).className,
  msg_user: stylex.props(styles.msg, styles.msg_user).className,
  msg_agent: stylex.props(styles.msg, styles.msg_agent).className,
  message_text: stylex.props(styles.message_text).className,
  greeting: stylex.props(styles.greeting).className,
  sender: stylex.props(styles.sender).className,
  result: stylex.props(styles.result).className,
  result_ok: stylex.props(styles.result, styles.result_ok).className,
  result_failed: stylex.props(styles.result, styles.result_failed).className,
  card_list: stylex.props(styles.card_list).className,
  data_card: stylex.props(styles.data_card).className,
  data_card_icon: stylex.props(styles.data_card_icon).className,
  transaction_direction: stylex.props(styles.transaction_direction).className,
  data_card_main: stylex.props(styles.data_card_main).className,
  data_card_heading: stylex.props(styles.data_card_heading).className,
  data_card_note: stylex.props(styles.data_card_note).className,
  data_card_meta: stylex.props(styles.data_card_meta).className,
  meta_label: stylex.props(styles.meta_label).className,
  card_actions: stylex.props(styles.card_actions).className,
  card_status: stylex.props(styles.card_status).className,
  step_status: stylex.props(styles.step_status).className,
  card_status_status_active: stylex.props(styles.card_status, styles.card_status_status_active).className,
  card_status_status_completed: stylex.props(styles.card_status_status_completed).className,
  card_status_status_complete: stylex.props(styles.card_status_status_complete).className,
  card_status_status_paid: stylex.props(styles.card_status_status_paid).className,
  card_status_status_success: stylex.props(styles.card_status_status_success).className,
  step_status_status_done: stylex.props(styles.step_status_status_done).className,
  step_status_status_completed: stylex.props(styles.step_status_status_completed).className,
  card_status_status_pending: stylex.props(styles.card_status, styles.card_status_status_pending).className,
  step_status_status_ready: stylex.props(styles.step_status_status_ready).className,
  step_status_status_pending: stylex.props(styles.step_status_status_pending).className,
  card_status_status_failed: stylex.props(styles.card_status, styles.card_status_status_failed).className,
  card_status_status_cancelled: stylex.props(styles.card_status_status_cancelled).className,
  card_status_status_declined: stylex.props(styles.card_status_status_declined).className,
  card_status_status_expired: stylex.props(styles.card_status_status_expired).className,
  step_status_status_failed: stylex.props(styles.step_status_status_failed).className,
  transaction_direction_sent: stylex.props(styles.transaction_direction, styles.transaction_direction_sent).className,
  transaction_direction_received: stylex.props(styles.transaction_direction, styles.transaction_direction_received).className,
  transaction_party: stylex.props(styles.transaction_party).className,
  amount_sent: stylex.props(styles.amount_sent).className,
  amount_received: stylex.props(styles.amount_received).className,
  weather_icon: stylex.props(styles.weather_icon).className,
  weather_response: stylex.props(styles.weather_response).className,
  weather_summary: stylex.props(styles.weather_summary).className,
  weather_card: stylex.props(styles.weather_card).className,
  weather_current: stylex.props(styles.weather_current).className,
  weather_temperature: stylex.props(styles.weather_temperature).className,
  weather_label: stylex.props(styles.weather_label).className,
  weather_details: stylex.props(styles.weather_details).className,
  weather_forecast: stylex.props(styles.weather_forecast).className,
  weather_day: stylex.props(styles.weather_day).className,
  weather_day_name: stylex.props(styles.weather_day_name).className,
  weather_day_icon: stylex.props(styles.weather_day_icon).className,
  weather_day_temperatures: stylex.props(styles.weather_day_temperatures).className,
  weather_day_label: stylex.props(styles.weather_day_label).className,
  step_list: stylex.props(styles.step_list).className,
  step: stylex.props(styles.step).className,
  step_head: stylex.props(styles.step_head).className,
  step_description: stylex.props(styles.step_description).className,
  step_note: stylex.props(styles.step_note).className,
  confirm_actions: stylex.props(styles.confirm_actions).className,
  confirm_state: stylex.props(styles.confirm_state).className,
  thinking: stylex.props(styles.thinking).className,
  empty: stylex.props(styles.empty).className,
  suggestions: stylex.props(styles.suggestions).className,
  suggestion: stylex.props(styles.suggestion).className,
  loading: stylex.props(styles.loading).className,
  skeleton_row: stylex.props(styles.skeleton_row).className,
  skeleton_row_user: stylex.props(styles.skeleton_row_user).className,
  load_error: stylex.props(styles.load_error).className,
  composer: stylex.props(styles.composer).className,
  composer_input: stylex.props(styles.composer_input).className,
  character_count: stylex.props(styles.character_count).className,
  character_count_near_limit: stylex.props(styles.character_count, styles.character_count_near_limit).className,
  suggestion_menu: stylex.props(styles.suggestion_menu).className,
  suggestion_trigger: stylex.props(styles.suggestion_trigger).className,
  suggestion_flyout: stylex.props(styles.suggestion_flyout).className,
  suggestion_option: stylex.props(styles.suggestion_option).className,
  message_pending: stylex.props(styles.message_pending).className,
  payment_card: stylex.props(styles.payment_card).className,
  layout_container: stylex.props(styles.layout_container).className,
  identity_heading: stylex.props(styles.identity_heading).className,
  identity_spinner: stylex.props(styles.identity_spinner).className,
  user_link: stylex.props(styles.user_link).className,
  msg_agent_card: stylex.props(styles.msg, styles.msg_agent, styles.msg_agent_card).className,
  msg_agent_weather: stylex.props(styles.msg, styles.msg_agent, styles.msg_agent_weather).className,
  result_icon: stylex.props(styles.result_icon).className,
  result_icon_ok: stylex.props(styles.result_icon_ok).className,
  result_icon_failed: stylex.props(styles.result_icon_failed).className,
  payment_heading: stylex.props(styles.data_card_heading, styles.payment_heading).className,
  heading_child: stylex.props(styles.heading_child).className,
  meta_mono: stylex.props(styles.meta_mono).className,
  card_action: stylex.props(styles.card_action).className,
  card_action_button: stylex.props(styles.card_action_button).className,
  weather_detail: stylex.props(styles.weather_detail).className,
  weather_day_after: stylex.props(styles.weather_day, styles.weather_day_after).className,
  thinking_spinner: stylex.props(styles.thinking_spinner).className,
  empty_avatar: stylex.props(styles.avatar, styles.empty_avatar).className,
  empty_heading: stylex.props(styles.empty_heading).className,
  load_error_alert: stylex.props(styles.load_error_alert).className,
  composer_textarea: stylex.props(styles.composer_textarea).className,
  composer_textarea_with_menu: stylex.props(styles.composer_textarea, styles.composer_textarea_with_menu).className,
  character_count_with_menu: stylex.props(styles.character_count, styles.character_count_with_menu).className,
  character_count_near_limit_with_menu: stylex.props(styles.character_count, styles.character_count_near_limit, styles.character_count_with_menu).className,
  submit_button: stylex.props(styles.submit_button).className,
  submit_spinner: stylex.props(styles.submit_spinner).className,
  reset_button: stylex.props(styles.reset_button).className,
  payment_card_actions: stylex.props(styles.payment_card_actions).className,
  confirm_action_button: stylex.props(styles.confirm_action_button).className,
};
