import * as stylex from '@stylexjs/stylex';

const drawer_in = stylex.keyframes({
  from: { transform: 'translateY(100%)', opacity: 0.4 },
  to: { transform: 'translateY(0)', opacity: 1 },
});

const drawer_out = stylex.keyframes({
  from: { transform: 'translateY(0)', opacity: 1 },
  to: { transform: 'translateY(100%)', opacity: 0.4 },
});

const styles = stylex.create({
  launcher: {
    position: 'fixed',
    right: '18px',
    bottom: 'calc(18px + var(--mpi-bottom-nav-h) + env(safe-area-inset-bottom))',
    zIndex: 151,
    width: '48px', height: '48px', padding: 0,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    translate: '0 0',
    marginRight: 'var(--mpi-tp-inset, 0px)',
    borderWidth: '1px', borderStyle: 'solid',
    borderColor: { default: 'var(--border)', ':hover': 'var(--brand)' },
    borderRadius: '16px',
    backgroundColor: 'var(--card)',
    boxShadow: 'var(--shadow)',
    color: { default: 'var(--fg)', ':hover': 'var(--brand)' },
    cursor: 'pointer',
    transform: { default: 'translateY(0)', ':hover': 'translateY(-3px)', ':active': 'translateY(0)' },
    transition: {
      default: 'translate 320ms cubic-bezier(0.32, 0.72, 0, 1), bottom 260ms cubic-bezier(0.32, 0.72, 0, 1), margin-right 260ms cubic-bezier(0.32, 0.72, 0, 1), transform 0.16s ease, color 0.16s, border-color 0.16s',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  launcher_stacked: {
    bottom: 'calc(78px + var(--mpi-bottom-nav-h) + env(safe-area-inset-bottom))',
  },
  launcher_out: {
    translate: '0 calc(100% + 18px + var(--mpi-bottom-nav-h) + env(safe-area-inset-bottom))',
    pointerEvents: 'none',
  },
  launcher_stacked_out: {
    translate: '0 calc(100% + 78px + var(--mpi-bottom-nav-h) + env(safe-area-inset-bottom))',
    pointerEvents: 'none',
  },
  drawer: {
    position: 'fixed',
    right: { default: '18px', '@media (max-width: 560px)': '10px' },
    left: { default: null, '@media (max-width: 560px)': '10px' },
    bottom: 'calc(var(--mpi-bottom-nav-h) + env(safe-area-inset-bottom))',
    zIndex: 150,
    width: { default: '396px', '@media (max-width: 560px)': 'auto' },
    maxWidth: { default: 'calc(100vw - 36px)', '@media (max-width: 560px)': 'none' },
    display: 'flex', flexDirection: 'column', overflow: 'hidden',
    marginRight: 'var(--mpi-tp-inset, 0px)',
    borderWidth: '1px', borderStyle: 'solid', borderColor: 'var(--border)',
    borderBottomWidth: 0, borderBottomStyle: 'none',
    borderRadius: '16px 16px 0 0',
    backgroundColor: 'var(--card)',
    boxShadow: { default: 'var(--shadow)', ':focus-visible': '0 0 0 2px var(--brand), var(--shadow)' },
    outline: 'none',
    transition: 'margin-right 260ms cubic-bezier(0.32, 0.72, 0, 1)',
    animationName: drawer_in,
    animationDuration: { default: '260ms', '@media (prefers-reduced-motion: reduce)': '1ms' },
    animationTimingFunction: 'cubic-bezier(0.32, 0.72, 0, 1)',
  },
  drawer_closing: {
    pointerEvents: 'none',
    animationName: drawer_out,
    animationDuration: { default: '200ms', '@media (prefers-reduced-motion: reduce)': '1ms' },
    animationTimingFunction: 'cubic-bezier(0.32, 0.72, 0, 1)',
    animationFillMode: 'forwards',
  },
  header: {
    display: 'flex', height: '50px', flexShrink: 0, alignItems: 'center', gap: '9px',
    padding: '0 8px 0 16px', borderBottomWidth: '1px', borderBottomStyle: 'solid',
    borderBottomColor: 'var(--border)', userSelect: 'none', WebkitUserSelect: 'none',
  },
  header_minimized: { borderBottomWidth: 0, borderBottomStyle: 'none', cursor: 'pointer' },
  icon: { display: 'flex', color: 'var(--muted)' },
  title: {
    flex: 1, minWidth: 0, overflow: 'hidden', color: 'var(--fg)',
    fontSize: '1.02rem', fontWeight: 700, textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  actions: { display: 'flex', alignItems: 'center', gap: '2px' },
  button: {
    display: 'flex',
    width: '32px',
    height: { default: '32px', '@media (pointer: coarse)': '44px' },
    minWidth: { default: null, '@media (pointer: coarse)': '44px' },
    alignItems: 'center', justifyContent: 'center', padding: 0,
    borderWidth: 0, borderStyle: 'none', borderRadius: '999px',
    backgroundColor: { default: 'transparent', ':hover': 'color-mix(in srgb, var(--fg) 10%, transparent)' },
    color: { default: 'var(--muted)', ':hover': 'var(--fg)' },
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    opacity: { default: 1, ':disabled': 0.45 },
    transition: 'color 0.12s, background 0.12s',
  },
  button_text: { width: 'auto', padding: '0 9px', fontSize: '0.66rem', fontWeight: 700, letterSpacing: '0.12em' },
  button_flip: { transform: 'rotate(180deg)' },
  body: {
    display: 'flex',
    height: { default: 'min(52dvh, 420px)', '@media (max-width: 560px)': 'min(56dvh, 380px)' },
    minHeight: 0, flexDirection: 'column',
  },
  body_minimized: { display: 'none' },
  loading: { display: 'flex', flex: 1, alignItems: 'center', justifyContent: 'center' },
  loading_spinner: { width: '22px', height: '22px', borderWidth: '2px' },
});

export const cli_drawer_classes = {
  launcher: stylex.props(styles.launcher).className,
  launcher_stacked: stylex.props(styles.launcher, styles.launcher_stacked).className,
  launcher_out: stylex.props(styles.launcher, styles.launcher_out).className,
  launcher_stacked_out: stylex.props(styles.launcher, styles.launcher_stacked, styles.launcher_stacked_out).className,
  drawer: stylex.props(styles.drawer).className,
  drawer_closing: stylex.props(styles.drawer, styles.drawer_closing).className,
  header: stylex.props(styles.header).className,
  header_minimized: stylex.props(styles.header, styles.header_minimized).className,
  icon: stylex.props(styles.icon).className,
  title: stylex.props(styles.title).className,
  actions: stylex.props(styles.actions).className,
  button: stylex.props(styles.button).className,
  button_text: stylex.props(styles.button, styles.button_text).className,
  button_flip: stylex.props(styles.button, styles.button_flip).className,
  body: stylex.props(styles.body).className,
  body_minimized: stylex.props(styles.body, styles.body_minimized).className,
  loading: stylex.props(styles.loading).className,
  loading_spinner: stylex.props(styles.loading_spinner).className,
};
