import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  body: {
    display: 'grid',
    gridTemplateColumns: { default: '240px 1fr', '@media (max-width: 900px)': '1fr' },
    flex: 1,
    minHeight: 0,
    alignItems: 'stretch',
    backgroundImage: { default: 'linear-gradient(to right, var(--bg) 239px, var(--border) 239px, var(--border) 240px, transparent 240px)', '@media (max-width: 900px)': 'none' },
  },
  body_settings: { overflow: 'hidden' },
  sidebar: {
    WebkitTouchCallout: { default: null, '@media (display-mode: standalone), (display-mode: fullscreen), (display-mode: minimal-ui)': 'none' },
    overscrollBehavior: { default: null, '@media (display-mode: standalone), (display-mode: fullscreen), (display-mode: minimal-ui)': 'contain' },
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'var(--border)',
    backgroundColor: 'var(--bg)',
    paddingTop: { default: '20px', '@media (max-width: 900px)': 'calc(20px + env(safe-area-inset-top))' },
    paddingRight: '16px',
    paddingBottom: { default: '20px', '@media (max-width: 900px)': 'env(safe-area-inset-bottom)' },
    paddingLeft: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    position: { default: 'sticky', '@media (max-width: 900px)': 'fixed' },
    top: { default: '92px', '@media (max-width: 900px)': 0 },
    left: { default: null, '@media (max-width: 900px)': 0 },
    alignSelf: 'start',
    maxHeight: { default: 'calc(100vh - 92px)', '@media (max-width: 900px)': 'none' },
    height: { default: null, '@media (max-width: 900px)': '100dvh' },
    width: { default: null, '@media (max-width: 900px)': '280px' },
    overflowY: 'auto',
    userSelect: 'none',
    transform: { default: null, '@media (max-width: 900px)': 'translateX(-100%)' },
    transition: { default: null, '@media (max-width: 900px)': 'transform 0.28s ease' },
    zIndex: { default: null, '@media (max-width: 900px)': 100 },
  },
  sidebar_open: {
    transform: { default: null, '@media (max-width: 900px)': 'translateX(0)' },
  },
  sidebar_settings: {
    position: { default: 'static', '@media (max-width: 900px)': 'fixed' },
    alignSelf: { default: 'stretch', '@media (max-width: 900px)': 'start' },
    maxHeight: 'none',
  },
  group_title: {
    margin: 0,
    fontSize: '0.7rem',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: { default: 'var(--muted)', ':hover': 'var(--fg)' },
  },
  group_toggle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: 0,
    margin: '0 0 8px',
    backgroundColor: 'transparent !important',
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    color: 'inherit !important',
    font: 'inherit',
    textAlign: 'left',
    transform: 'none !important',
  },
  group_chevron: {
    display: 'flex',
    alignItems: 'center',
    color: 'var(--muted)',
    opacity: 0.7,
    transition: 'transform 0.16s ease',
    transform: 'rotate(0deg)',
  },
  group_chevron_collapsed: { transform: 'rotate(-90deg)' },
  links: { display: 'flex', flexDirection: 'column', gap: '6px' },
  links_collapsed: { display: 'none' },
  link: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 12px',
    borderRadius: '8px',
    color: 'var(--fg)',
    fontSize: '0.9rem',
    textDecoration: 'none',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'transparent',
    transition: 'background 320ms ease, color 320ms ease, opacity 320ms ease',
    backgroundColor: { default: 'transparent', ':hover': 'var(--bg-elev)' },
    minHeight: { default: null, '@media (pointer: coarse)': '46px' },
  },
  link_active: {
    backgroundColor: { default: 'var(--brand)', ':hover': 'var(--brand-dark)' },
    color: 'var(--brand-text)',
    fontWeight: 500,
  },
  link_active_parent: {
    backgroundColor: { default: 'var(--brand)', ':hover': 'var(--bg-elev)' },
    color: 'var(--brand-text)',
    fontWeight: 500,
    opacity: { default: 0.55, ':hover': 1 },
  },
  link_icon: {
    flexShrink: 0,
    opacity: { default: 0.75, ':hover': 1 },
    transition: 'opacity 320ms ease',
  },
  link_icon_active: { opacity: 1 },
  link_icon_active_parent: { opacity: 0.75 },
  icon_wrap: { position: 'relative', display: 'inline-flex', flexShrink: 0 },
  badge: {
    position: 'absolute', top: '-6px', right: '-8px', minWidth: '15px', height: '15px',
    padding: '0 3px', borderRadius: '999px', backgroundColor: 'var(--brand)',
    color: 'var(--brand-text)', fontSize: '0.62rem', fontWeight: 700,
    lineHeight: '15px', textAlign: 'center',
  },
  mobile_header: {
    display: { default: 'none', '@media (max-width: 900px)': 'flex' },
    alignItems: 'center', justifyContent: 'space-between',
  },
  sidebar_logo: { display: 'block' },
  close_btn: {
    display: { default: 'none', '@media (max-width: 900px)': 'block' },
    backgroundColor: 'transparent', borderWidth: 0, borderStyle: 'none',
    color: 'var(--fg)', fontSize: '1.5rem', cursor: 'pointer', alignSelf: 'flex-end',
  },
  overlay: {
    position: 'fixed', inset: 0, backgroundColor: 'rgba(0, 0, 0, 0.5)',
    opacity: 0, pointerEvents: 'none', transition: 'opacity 0.25s ease, margin-right var(--mpi-tp-ease)', zIndex: 90,
    marginRight: 'var(--mpi-tp-inset)',
  },
  overlay_open: { opacity: 1, pointerEvents: 'auto' },
  sidebar_logout: { marginTop: 'auto' },
  main: {
    paddingTop: { default: '28px', '@media (max-width: 900px)': '18px' },
    paddingRight: { default: '32px', '@media (max-width: 900px)': 'max(14px, env(safe-area-inset-right))' },
    paddingBottom: { default: 'calc(28px + var(--mpi-bottom-nav-h))', '@media (max-width: 900px)': 'calc(18px + var(--mpi-bottom-nav-h))' },
    paddingLeft: { default: '16px', '@media (max-width: 900px)': 'max(14px, env(safe-area-inset-left))' },
    minWidth: 0, display: 'flex', flexDirection: 'column',
    transition: { default: null, '@media (max-width: 900px)': 'padding-bottom 280ms cubic-bezier(0.32, 0.72, 0, 1)', '@media (prefers-reduced-motion: reduce)': 'none' },
  },
  main_settings: {
    paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0,
    flexGrow: 1, flexShrink: 1, flexBasis: '0%', minHeight: 0, overflow: 'hidden',
  },
  wrap: { margin: '0 auto 0 0', display: 'flex', flexDirection: 'column', flex: 1, width: '100%' },
  wrap_settings: {
    maxWidth: '100%', margin: 0, flexGrow: 1, flexShrink: 1,
    flexBasis: '0%', minHeight: 0, overflow: 'hidden',
  },
});

export const layout_classes = {
  body: stylex.props(styles.body).className,
  body_settings: stylex.props(styles.body, styles.body_settings).className,
  sidebar: stylex.props(styles.sidebar).className,
  sidebar_open: stylex.props(styles.sidebar, styles.sidebar_open).className,
  sidebar_settings: stylex.props(styles.sidebar, styles.sidebar_settings).className,
  sidebar_settings_open: stylex.props(styles.sidebar, styles.sidebar_settings, styles.sidebar_open).className,
  group_title: stylex.props(styles.group_title).className,
  group_toggle: stylex.props(styles.group_toggle).className,
  group_chevron: stylex.props(styles.group_chevron).className,
  group_chevron_collapsed: stylex.props(styles.group_chevron, styles.group_chevron_collapsed).className,
  links: stylex.props(styles.links).className,
  links_collapsed: stylex.props(styles.links, styles.links_collapsed).className,
  link: stylex.props(styles.link).className,
  link_active: stylex.props(styles.link, styles.link_active).className,
  link_active_parent: stylex.props(styles.link, styles.link_active_parent).className,
  link_icon: stylex.props(styles.link_icon).className,
  link_icon_active: stylex.props(styles.link_icon, styles.link_icon_active).className,
  link_icon_active_parent: stylex.props(styles.link_icon, styles.link_icon_active_parent).className,
  mobile_header: stylex.props(styles.mobile_header).className,
  sidebar_logo: stylex.props(styles.sidebar_logo).className,
  close_btn: stylex.props(styles.close_btn).className,
  overlay: stylex.props(styles.overlay).className,
  overlay_open: stylex.props(styles.overlay, styles.overlay_open).className,
  main: stylex.props(styles.main).className,
  main_settings: stylex.props(styles.main, styles.main_settings).className,
  wrap: stylex.props(styles.wrap).className,
  wrap_settings: stylex.props(styles.wrap, styles.wrap_settings).className,
};
