import * as stylex from '@stylexjs/stylex';
const team_highlight = stylex.keyframes({ '0%, 100%': { borderColor: 'var(--border)', backgroundColor: 'var(--card)' }, '50%': { borderColor: 'var(--brand)', backgroundColor: 'color-mix(in srgb, var(--brand) 22%, var(--card))' } });

const styles = stylex.create({
  lb_row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "12px",
    paddingRight: "16px",
    paddingBottom: "12px",
    paddingLeft: "16px",
    borderBottomWidth: {
      default: "1px",
      ":last-child": 0,
    },
    borderBottomStyle: {
      default: "solid",
      ":last-child": "none",
    },
    borderBottomColor: "var(--border)",
  },
  lb_rank: {
    fontWeight: 700,
    fontSize: "1.1rem",
    width: "32px",
    color: "var(--muted)",
  },
  lb_rank_top_1: {
    color: "gold",
  },
  lb_rank_top_2: {
    color: "silver",
  },
  lb_rank_top_3: {
    color: "#cd7f32",
  },
  lb_username: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    paddingTop: 0,
    paddingRight: "12px",
    paddingBottom: 0,
    paddingLeft: "12px",
    fontWeight: 500,
    fontSize: { default: null, '@media (max-width: 900px)': '0.95rem' },
  },
  lb_balance: {
    color: "var(--brand)",
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    fontSize: { default: null, '@media (max-width: 900px)': '0.95rem' },
  },
  team_card: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    gap: "6px",
    height: "100%",
  },
  team_header: {
    display: "flex",
    gap: "12px",
    alignItems: "flex-start",
    justifyContent: "center",
    width: "100%",
  },
  team_header_info: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    textAlign: "left",
    minWidth: 0,
  },
  team_avatar: {
    width: "72px",
    height: "72px",
    borderRadius: "50%",
    objectFit: "cover",
    userSelect: "none",
    cursor: "pointer",
    flexShrink: 0,
  },
  team_name: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexWrap: "wrap",
    fontWeight: 700,
    fontSize: "1.05rem",
  },
  team_role: {
    color: "var(--brand)",
    fontWeight: 500,
    fontSize: "0.85rem",
  },
  team_pride_flags: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
  },
  team_joined: {
    fontSize: "0.78rem",
    color: "var(--muted)",
  },
  team_socials: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: "auto",
    paddingTop: "12px",
  },
  team_social_link_btn: {
    width: "40px",
    height: "40px",
    paddingTop: "9px",
    paddingRight: "9px",
    paddingBottom: "9px",
    paddingLeft: "9px",
    borderRadius: "50%",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "40px",
    color: {
      default: null,
      ":hover": "var(--brand)",
    },
    transform: {
      default: null,
      ":hover": "translateY(-1px)",
      ":active": "translateY(1px)",
    },
    outlineWidth: {
      default: null,
      ":focus-visible": "2px",
    },
    outlineStyle: {
      default: null,
      ":focus-visible": "solid",
    },
    outlineColor: {
      default: null,
      ":focus-visible": "var(--brand)",
    },
    outlineOffset: {
      default: null,
      ":focus-visible": "2px",
    },
  },
  team_social_icon: {
    display: "block",
    width: "100%",
    height: "100%",
  },
  team_contributions: {
    listStyle: "disc",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingLeft: "18px",
    textAlign: "left",
    fontSize: "0.85rem",
    color: "var(--fg)",
  },
  team_timeline: {
    listStyle: "none",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: "18px",
    position: "relative",
    textAlign: "left",
    '::before': {
      content: '""',
      position: 'absolute',
      left: 4,
      top: 4,
      bottom: 4,
      width: 1,
      backgroundColor: 'var(--border)',
    },
  },
  timeline_item: {
    position: "relative",
    paddingBottom: {
      default: "12px",
      ":last-child": 0,
    },
    '::before': {
      content: '""',
      position: 'absolute',
      left: -18,
      top: 5,
      width: 9,
      height: 9,
      borderRadius: '50%',
      backgroundColor: 'var(--brand)',
      borderWidth: 2,
      borderStyle: 'solid',
      borderColor: 'var(--card)',
    },
  },
  timeline_heading: {
    fontSize: "0.85rem",
    fontWeight: 600,
    color: "var(--fg)",
  },
  timeline_date: {
    fontSize: "0.75rem",
    color: "var(--muted)",
  },
  roles_toggle: {
    position: "absolute",
    width: "1px",
    height: "1px",
    opacity: 0,
    pointerEvents: "none",
  },
  roles_toggle_label: {
    display: "block",
    marginTop: 0,
    cursor: "pointer",
    fontSize: "0.75rem",
    color: "var(--brand-contrasted, var(--brand))",
    textAlign: "left",
    textDecoration: {
      default: null,
      ":hover": "underline",
    },
  },
  pride_flag: {
    display: "inline-block",
    width: "26px",
    height: "16px",
    borderRadius: "3px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    boxShadow: "inset 0 0.5px 0 0 rgba(255, 255, 255, 0.2)",
    backgroundSize: "cover",
  },
  pride_flag_avatar: {
    position: "absolute !important",
    inset: "0 !important",
    width: "100% !important",
    height: "100% !important",
    borderWidth: "0 !important",
    borderStyle: "none !important",
    borderRadius: "inherit !important",
  },
  pride_flag__rainbow: {
    backgroundImage: "linear-gradient( to bottom, #e40303 0 16.66%, #ff8c00 16.66% 33.33%, #ffed00 33.33% 50%, #008026 50% 66.66%, #004dff 66.66% 83.33%, #750787 83.33% 100% )",
  },
  pride_flag__progress: {
    backgroundImage: 'linear-gradient(to right, transparent 40%, #ffffff 40% 100%), linear-gradient(to right, transparent 40%, #ffafc8 40% 100%), linear-gradient(to right, transparent 40%, #74d7ee 40% 100%), linear-gradient(135deg, #000000 0 12%, #613915 12% 24%, transparent 24%), linear-gradient(to bottom, #e40303 0 16.66%, #ff8c00 16.66% 33.33%, #ffed00 33.33% 50%, #008026 50% 66.66%, #004dff 66.66% 83.33%, #750787 83.33% 100%)',
    backgroundPosition: '0 0, 0 100%, 0 50%, 0 0, 0 0',
    backgroundSize: '100% 25%, 100% 25%, 100% 25%, auto, auto',
    backgroundRepeat: 'no-repeat, no-repeat, no-repeat, repeat, repeat',
  },
  pride_flag__trans: {
    backgroundImage: "linear-gradient( to bottom, #5bcefa 0 20%, #f5a9b8 20% 40%, #ffffff 40% 60%, #f5a9b8 60% 80%, #5bcefa 80% 100% )",
  },
  pride_flag__bisexual: {
    backgroundImage: "linear-gradient( to bottom, #d60270 0 40%, #9b4f96 40% 60%, #0038a8 60% 100% )",
  },
  pride_flag__pansexual: {
    backgroundImage: "linear-gradient( to bottom, #ff218c 0 33.33%, #ffd800 33.33% 66.66%, #21b1ff 66.66% 100% )",
  },
  pride_flag__nonbinary: {
    backgroundImage: "linear-gradient( to bottom, #fcf434 0 25%, #ffffff 25% 50%, #9c59d1 50% 75%, #2c2c2c 75% 100% )",
  },
  pride_flag__lesbian: {
    backgroundImage: "linear-gradient( to bottom, #d52d00 0 20%, #ff9a56 20% 40%, #ffffff 40% 60%, #d362a4 60% 80%, #a30262 80% 100% )",
  },
  pride_flag__mlm: {
    backgroundImage: "linear-gradient( to bottom, #078d70 0 14.28%, #26ceaa 14.28% 28.57%, #98e8c1 28.57% 42.85%, #ffffff 42.85% 57.14%, #7bade2 57.14% 71.42%, #5049cc 71.42% 85.71%, #3d1a78 85.71% 100% )",
  },
  pride_flag__asexual: {
    backgroundImage: "linear-gradient( to bottom, #000000 0 25%, #a3a3a3 25% 50%, #ffffff 50% 75%, #800080 75% 100% )",
  },
  pride_flag__genderfluid: {
    backgroundImage: "linear-gradient( to bottom, #ff75a2 0 20%, #ffffff 20% 40%, #be18d6 40% 60%, #000000 60% 80%, #333ebd 80% 100% )",
  },
  pride_flag__aromantic: {
    backgroundImage: "linear-gradient( to bottom, #3da542 0 20%, #a7d379 20% 40%, #ffffff 40% 60%, #a9a9a9 60% 80%, #000000 80% 100% )",
  },
  pride_flag__agender: {
    backgroundImage: "linear-gradient( to bottom, #000000 0 14.28%, #b9b9b9 14.28% 28.57%, #ffffff 28.57% 42.85%, #b8f483 42.85% 57.14%, #ffffff 57.14% 71.42%, #b9b9b9 71.42% 85.71%, #000000 85.71% 100% )",
  },
  pride_flag__intersex: {
    backgroundColor: "#ffd800",
    position: "relative",
    '::after': {
      content: '""',
      position: 'absolute',
      top: '50%',
      left: '50%',
      width: 7,
      height: 7,
      transform: 'translate(-50%, -50%)',
      borderRadius: '50%',
      borderWidth: 1.5,
      borderStyle: 'solid',
      borderColor: '#7902aa',
    },
  },
  team_quote: {
    fontStyle: "italic",
    color: "var(--muted)",
    fontSize: "0.85rem",
    marginTop: "4px",
    marginRight: 0,
    marginBottom: "4px",
    marginLeft: 0,
  },
  team_section_label: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "var(--muted)",
    marginTop: "10px",
    marginBottom: "4px",
    textAlign: "left",
  },
  team_card__highlight: {
    animationName: {
      default: team_highlight,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    animationDuration: '0.7s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 3,
    scrollMarginBlock: "calc(var(--mpi-header-h, 92px) + 16px)",
    borderColor: {
      default: null,
      "@media (prefers-reduced-motion: reduce)": "var(--brand)",
    },
  },
  team_status_heading: {
    marginTop: "32px",
    marginBottom: "14px",
    paddingBottom: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
  },
  team_heading_row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap",
  },
  team_globe_wrap: {
    position: "relative",
    width: "100%",
    height: "min(68vh, 620px)",
    minHeight: "380px",
    marginTop: "14px",
    borderRadius: "14px",
    overflow: "hidden",
    backgroundImage: "radial-gradient(120% 90% at 50% 0%, var(--card) 0%, var(--bg) 78%)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    cursor: {
      default: "grab",
      ":active": "grabbing",
    },
  },
  team_globe_loading: {
    position: "absolute",
    inset: 0,
    display: "grid",
    placeItems: "center",
  },
  team_globe_tip: {
    backgroundColor: "var(--surface-2, #222)",
    color: "var(--text)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "8px",
    paddingTop: "6px",
    paddingRight: "10px",
    paddingBottom: "6px",
    paddingLeft: "10px",
    fontSize: "0.82rem",
    fontWeight: 600,
    whiteSpace: "nowrap",
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.3)",
  },
  team_card__modal: {
    height: "auto",
  },
  globe_country_label: {
    fontSize: "calc(8px * var(--globe-label-scale, 1))",
    opacity: "var(--globe-label-opacity, 0)",
    fontWeight: 500,
    letterSpacing: "0.06em",
    color: "var(--globe-country-label-color)",
    textShadow: "var(--globe-country-label-shadow)",
    whiteSpace: "nowrap",
    pointerEvents: "none",
    userSelect: "none",
    transition: "opacity 0.25s ease",
  },
  globe_country_label_is_hidden: {
    opacity: 0,
  },
  team_contribution_item: {
    paddingTop: 1,
    paddingBottom: 1,
  },
  team_align_stretch: {
    alignSelf: 'stretch',
  },
  team_heading_title: {
    marginBottom: 0,
  },
  team_globe_tip_role: {
    color: 'var(--brand)',
    fontWeight: 500,
  },
  timeline_item_hidden: {
    display: 'none',
  },
  timeline_item_collapsed_last: {
    paddingBottom: 0,
  },
});

export const lbteam_classes = {
  lb_row: stylex.props(styles.lb_row).className,
  lb_rank: stylex.props(styles.lb_rank).className,
  lb_rank_top_1: stylex.props(styles.lb_rank, styles.lb_rank_top_1).className,
  lb_rank_top_2: stylex.props(styles.lb_rank, styles.lb_rank_top_2).className,
  lb_rank_top_3: stylex.props(styles.lb_rank, styles.lb_rank_top_3).className,
  lb_username: stylex.props(styles.lb_username).className,
  lb_balance: stylex.props(styles.lb_balance).className,
  team_card: stylex.props(styles.team_card).className,
  team_header: stylex.props(styles.team_header).className,
  team_header_info: stylex.props(styles.team_header_info).className,
  team_avatar: stylex.props(styles.team_avatar).className,
  team_name: stylex.props(styles.team_name).className,
  team_role: stylex.props(styles.team_role).className,
  team_pride_flags: stylex.props(styles.team_pride_flags).className,
  team_joined: stylex.props(styles.team_joined).className,
  team_socials: stylex.props(styles.team_socials).className,
  team_social_link_btn: stylex.props(styles.team_social_link_btn).className,
  team_social_icon: stylex.props(styles.team_social_icon).className,
  team_contributions: stylex.props(styles.team_contributions).className,
  team_timeline: stylex.props(styles.team_timeline).className,
  timeline_item: stylex.props(styles.timeline_item).className,
  timeline_heading: stylex.props(styles.timeline_heading).className,
  timeline_date: stylex.props(styles.timeline_date).className,
  roles_toggle: stylex.props(styles.roles_toggle).className,
  roles_toggle_label: stylex.props(styles.roles_toggle_label).className,
  pride_flag: stylex.props(styles.pride_flag).className,
  pride_flag_avatar: stylex.props(styles.pride_flag_avatar).className,
  pride_flag__rainbow: stylex.props(styles.pride_flag, styles.pride_flag__rainbow).className,
  pride_flag__progress: stylex.props(styles.pride_flag, styles.pride_flag__progress).className,
  pride_flag__trans: stylex.props(styles.pride_flag, styles.pride_flag__trans).className,
  pride_flag__bisexual: stylex.props(styles.pride_flag, styles.pride_flag__bisexual).className,
  pride_flag__pansexual: stylex.props(styles.pride_flag, styles.pride_flag__pansexual).className,
  pride_flag__nonbinary: stylex.props(styles.pride_flag, styles.pride_flag__nonbinary).className,
  pride_flag__lesbian: stylex.props(styles.pride_flag, styles.pride_flag__lesbian).className,
  pride_flag__mlm: stylex.props(styles.pride_flag, styles.pride_flag__mlm).className,
  pride_flag__asexual: stylex.props(styles.pride_flag, styles.pride_flag__asexual).className,
  pride_flag__genderfluid: stylex.props(styles.pride_flag, styles.pride_flag__genderfluid).className,
  pride_flag__aromantic: stylex.props(styles.pride_flag, styles.pride_flag__aromantic).className,
  pride_flag__agender: stylex.props(styles.pride_flag, styles.pride_flag__agender).className,
  pride_flag__intersex: stylex.props(styles.pride_flag, styles.pride_flag__intersex).className,
  team_quote: stylex.props(styles.team_quote).className,
  team_section_label: stylex.props(styles.team_section_label).className,
  team_card__highlight: stylex.props(styles.team_card, styles.team_card__highlight).className,
  team_status_heading: stylex.props(styles.team_status_heading).className,
  team_heading_row: stylex.props(styles.team_heading_row).className,
  team_globe_wrap: stylex.props(styles.team_globe_wrap).className,
  team_globe_loading: stylex.props(styles.team_globe_loading).className,
  team_globe_tip: stylex.props(styles.team_globe_tip).className,
  team_card__modal: stylex.props(styles.team_card, styles.team_card__modal).className,
  globe_country_label: stylex.props(styles.globe_country_label).className,
  globe_country_label_is_hidden: stylex.props(styles.globe_country_label, styles.globe_country_label_is_hidden).className,
  team_contribution_item: stylex.props(styles.team_contribution_item).className,
  team_align_stretch: stylex.props(styles.team_align_stretch).className,
  team_heading_title: stylex.props(styles.team_heading_title).className,
  team_globe_tip_role: stylex.props(styles.team_globe_tip_role).className,
  timeline_item_hidden: stylex.props(styles.timeline_item, styles.timeline_item_hidden).className,
  timeline_item_collapsed_last: stylex.props(styles.timeline_item, styles.timeline_item_collapsed_last).className,
};

export function pride_flag_class(flag: string): string {
  const name = `pride_flag__${flag.toLowerCase().replace(/[^a-z0-9_]/g, '_')}` as keyof typeof lbteam_classes;
  return lbteam_classes[name] ?? lbteam_classes.pride_flag ?? '';
}
