import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  prose: { whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' },
  banner: { display: 'block', width: '100%', maxHeight: '240px', objectFit: 'cover', borderRadius: 'var(--radius)' },
  avatar: { display: 'block', width: '128px', height: '128px', borderWidth: '2px', borderStyle: 'solid', borderColor: 'var(--border)', borderRadius: 'inherit', objectFit: 'cover', position: 'relative', boxSizing: 'border-box' },
  avatar_frame: { position: 'relative', width: '128px', height: '128px', borderRadius: '24px' },
  avatar_frame_with_banner: { marginTop: '-64px', marginLeft: '8px' },
  avatar_accessory: { position: 'absolute', inset: 0, width: '100%', height: '100%', transform: 'translateY(-26%)', overflow: 'visible', pointerEvents: 'none' },
  image: { maxWidth: '100%', maxHeight: '320px', objectFit: 'contain', borderRadius: 'var(--radius)' },
  section_summary: { cursor: 'pointer', listStyle: 'none', '::-webkit-details-marker': { display: 'none' } },
  discover_tabs: {
    display: 'inline-flex', alignSelf: 'flex-start', width: 'fit-content', maxWidth: '100%', gap: '4px', padding: '4px', marginBottom: '20px',
    backgroundColor: 'var(--card-soft)', borderWidth: '1px', borderStyle: 'solid', borderColor: 'var(--border)', borderRadius: 'var(--radius)',
  },
  discover_tab: {
    borderWidth: 0, borderStyle: 'none', borderRadius: '8px', backgroundColor: { default: 'transparent', ':hover': 'var(--bg-elev)' },
    color: 'var(--muted)', padding: '9px 16px', fontFamily: 'inherit', fontSize: '0.95rem', cursor: 'pointer',
  },
  discover_tab_active: { backgroundColor: 'var(--bg)', color: 'var(--fg)', fontWeight: 600 },
  discover_search: { display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap', marginBottom: '24px' },
  discover_search_field: { flexGrow: 0, flexShrink: 1, flexBasis: '680px', minWidth: 'min(100%, 240px)', maxWidth: '100%' },
  discover_search_input: { height: '44px', paddingTop: '18px', paddingBottom: '4px' },
  discover_search_button: { height: '44px' },
  discover_grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '12px' },
  discover_card: { padding: '16px', minWidth: 0 },
  discover_card_header: { display: 'flex', gap: '12px', alignItems: 'flex-start', minWidth: 0 },
  discover_card_avatar: { width: '48px', height: '48px', borderRadius: '10px', objectFit: 'cover', flexShrink: 0 },
  discover_card_content: { minWidth: 0, flexGrow: 1, flexShrink: 1, flexBasis: '0%' },
  discover_card_name: { display: 'flex', alignItems: 'center', gap: '4px', fontSize: '1rem', fontWeight: 700, minWidth: 0 },
  discover_card_identity: { display: 'flex', alignItems: 'center', gap: '6px', marginTop: '2px', flexWrap: 'wrap', color: 'var(--muted)', fontSize: '0.85rem' },
  discover_card_status: { marginTop: '2px', color: 'var(--muted)', fontSize: '0.85rem', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  discover_card_bio: { marginTop: '6px', color: 'var(--muted)', fontSize: '0.9rem', lineHeight: 1.4, overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' },
  discover_card_meta: { display: 'flex', alignItems: 'center', gap: '14px', marginTop: '10px', color: 'var(--muted)', fontSize: '0.8rem', flexWrap: 'wrap' },
  discover_card_meta_item: { display: 'inline-flex', alignItems: 'center', gap: '4px' },
});

export const profile_classes = {
  prose: stylex.props(styles.prose).className,
  banner: stylex.props(styles.banner).className,
  avatar: stylex.props(styles.avatar).className,
  avatar_frame: stylex.props(styles.avatar_frame).className,
  avatar_frame_with_banner: stylex.props(styles.avatar_frame, styles.avatar_frame_with_banner).className,
  avatar_accessory: stylex.props(styles.avatar_accessory).className,
  image: stylex.props(styles.image).className,
  section_summary: stylex.props(styles.section_summary).className,
  discover_tabs: stylex.props(styles.discover_tabs).className,
  discover_tab: stylex.props(styles.discover_tab).className,
  discover_tab_active: stylex.props(styles.discover_tab, styles.discover_tab_active).className,
  discover_search: stylex.props(styles.discover_search).className,
  discover_search_field: stylex.props(styles.discover_search_field).className,
  discover_search_input: stylex.props(styles.discover_search_input).className,
  discover_search_button: stylex.props(styles.discover_search_button).className,
  discover_grid: stylex.props(styles.discover_grid).className,
  discover_card: stylex.props(styles.discover_card).className,
  discover_card_header: stylex.props(styles.discover_card_header).className,
  discover_card_avatar: stylex.props(styles.discover_card_avatar).className,
  discover_card_content: stylex.props(styles.discover_card_content).className,
  discover_card_name: stylex.props(styles.discover_card_name).className,
  discover_card_identity: stylex.props(styles.discover_card_identity).className,
  discover_card_status: stylex.props(styles.discover_card_status).className,
  discover_card_bio: stylex.props(styles.discover_card_bio).className,
  discover_card_meta: stylex.props(styles.discover_card_meta).className,
  discover_card_meta_item: stylex.props(styles.discover_card_meta_item).className,
};
