import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  layout: {
    display: 'grid',
    gridTemplateColumns: { default: '300px 1fr', '@media (max-width: 700px)': '1fr' },
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
    minHeight: 0,
    borderTopWidth: { default: null, '@media (max-width: 700px)': 0 },
    borderTopStyle: { default: null, '@media (max-width: 700px)': 'none' },
  },
  nav: {
    WebkitTouchCallout: { default: null, '@media (display-mode: standalone), (display-mode: fullscreen), (display-mode: minimal-ui)': 'none' },
    display: 'flex',
    flexDirection: 'column',
    borderRightWidth: { default: '1px', '@media (max-width: 700px)': 0 },
    borderRightStyle: { default: 'solid', '@media (max-width: 700px)': 'none' },
    borderRightColor: 'var(--border)',
    minHeight: 0,
    overflow: 'hidden',
  },
  nav_hidden: {
    display: { default: 'flex', '@media (max-width: 700px)': 'none' },
  },
  nav_header: {
    display: 'flex',
    alignItems: 'center',
    height: '64px',
    padding: '0 20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--border)',
    flexShrink: 0,
  },
  nav_heading: { fontSize: '1.4rem', fontWeight: 700, margin: 0 },
  nav_list: { flex: 1, overflowY: 'auto', padding: '8px 0' },
  nav_item: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    width: '100%', padding: '15px 20px',
    borderWidth: 0, borderStyle: 'none',
    borderLeftWidth: '3px', borderLeftStyle: 'solid',
    borderLeftColor: 'transparent',
    backgroundColor: { default: 'transparent', ':hover': 'var(--bg-elev)' },
    color: { default: 'var(--fg)', ':hover': 'inherit' },
    textAlign: 'left', textDecoration: 'none', cursor: 'pointer',
    fontSize: '0.95rem', fontFamily: 'inherit',
    transition: 'background 0.12s ease', gap: '10px',
    minHeight: { default: null, '@media (pointer: coarse)': '46px' },
  },
  nav_item_active: {
    backgroundColor: 'var(--bg-elev)',
    borderLeftColor: 'var(--brand)',
    fontWeight: 500,
  },
  nav_item_label: {
    flexGrow: 1, flexShrink: 1, flexBasis: '0%', minWidth: 0,
    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
  },
  nav_item_chevron: { color: 'var(--muted)', flexShrink: 0, display: 'flex', alignItems: 'center' },
  nav_footer: {
    flexShrink: 0, padding: '12px 20px 16px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'var(--border)',
  },
  nav_footer_text: { margin: 0, fontSize: '0.78rem', lineHeight: 1.6 },
  detail: {
    display: { default: 'flex', '@media (max-width: 700px)': 'none' },
    flexDirection: 'column', minHeight: 0, overflow: 'hidden',
  },
  detail_visible: {
    display: 'flex',
  },
  detail_header: {
    display: 'flex', alignItems: 'center', gap: '12px', padding: '0 28px',
    height: '64px', borderBottomWidth: '1px', borderBottomStyle: 'solid',
    borderBottomColor: 'var(--border)', fontWeight: 700, fontSize: '1.15rem',
    flexShrink: 0, position: 'sticky', top: 0,
    backgroundColor: 'var(--bg)', zIndex: 1,
  },
  detail_back: {
    display: { default: 'none', '@media (max-width: 700px)': 'flex' },
    backgroundColor: { default: 'transparent', ':hover': 'var(--bg-elev)' },
    borderWidth: 0, borderStyle: 'none', color: 'var(--fg)',
    cursor: 'pointer', padding: '7px', alignItems: 'center', justifyContent: 'center',
    borderRadius: '50%', transition: 'background 0.12s ease',
    flexShrink: 0, marginLeft: '-7px',
  },
  detail_scroll: { flex: 1, overflowY: 'auto' },
  detail_content: {
    paddingTop: { default: '28px', '@media (max-width: 900px)': '20px' },
    paddingRight: { default: '28px', '@media (max-width: 900px)': 'max(18px, env(safe-area-inset-right))' },
    paddingBottom: '28px',
    paddingLeft: { default: '28px', '@media (max-width: 900px)': 'max(18px, env(safe-area-inset-left))' },
  },
});

export const settings_classes = {
  layout: stylex.props(styles.layout).className,
  nav: stylex.props(styles.nav).className,
  nav_hidden: stylex.props(styles.nav, styles.nav_hidden).className,
  nav_header: stylex.props(styles.nav_header).className,
  nav_heading: stylex.props(styles.nav_heading).className,
  nav_list: stylex.props(styles.nav_list).className,
  nav_item: stylex.props(styles.nav_item).className,
  nav_item_active: stylex.props(styles.nav_item, styles.nav_item_active).className,
  nav_item_label: stylex.props(styles.nav_item_label).className,
  nav_item_chevron: stylex.props(styles.nav_item_chevron).className,
  nav_footer: stylex.props(styles.nav_footer).className,
  nav_footer_text: stylex.props(styles.nav_footer_text).className,
  detail: stylex.props(styles.detail).className,
  detail_visible: stylex.props(styles.detail, styles.detail_visible).className,
  detail_header: stylex.props(styles.detail_header).className,
  detail_back: stylex.props(styles.detail_back).className,
  detail_scroll: stylex.props(styles.detail_scroll).className,
  detail_content: stylex.props(styles.detail_content).className,
};
