import * as stylex from '@stylexjs/stylex';
const dropdown_in = stylex.keyframes({ from: { opacity: 0, transform: 'translateY(-4px) scale(0.98)' }, to: { opacity: 1, transform: 'translateY(0) scale(1)' } });
const dropdown_out = stylex.keyframes({ from: { opacity: 1, transform: 'translateY(0) scale(1)' }, to: { opacity: 0, transform: 'translateY(-4px) scale(0.98)' } });

const styles = stylex.create({
  mpi_shell: {
    display: "flex",
    flexDirection: "column",
    minHeight: "calc(100dvh - var(--mpi-bottom-nav-h) - env(safe-area-inset-bottom))",
    marginRight: 'var(--mpi-tp-inset)',
    transition: 'margin-right var(--mpi-tp-ease)',
  },
  mpi_shell_settings: {
    height: 'calc(100dvh - var(--mpi-bottom-nav-h) - env(safe-area-inset-bottom))',
    overflow: 'hidden',
    transition: { default: null, '@media (max-width: 900px)': 'margin-right var(--mpi-tp-ease), height 280ms cubic-bezier(0.32, 0.72, 0, 1)', '@media (max-width: 900px) and (prefers-reduced-motion: reduce)': 'none' },
  },
  mpi_sticky_top: {
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  mpi_header: {
    WebkitTouchCallout: { default: null, '@media (display-mode: standalone), (display-mode: fullscreen), (display-mode: minimal-ui)': 'none' },
    position: { default: null, '@media (display-mode: standalone), (display-mode: fullscreen), (display-mode: minimal-ui)': 'relative' },
    backgroundColor: "var(--bg)",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
    paddingTop: "env(safe-area-inset-top)",
  },
  verification_banner_stack: {
    display: "flex",
    flexDirection: "column",
  },
  mpi_header_row: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    paddingTop: "10px",
    paddingRight: {
      default: "16px",
      "@media (max-width: 900px)": "max(16px, env(safe-area-inset-right))",
    },
    paddingBottom: "10px",
    paddingLeft: {
      default: "16px",
      "@media (max-width: 900px)": "max(16px, env(safe-area-inset-left))",
    },
  },
  mpi_header_logo: {
    height: {
      default: "38px",
      "@media (max-width: 900px)": "32px",
    },
    width: "auto",
    display: "block",
  },
  mpi_header_spacer: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  hamburger_btn: {
    display: {
      default: "none",
      "@media (max-width: 900px)": "inline-flex",
    },
    backgroundColor: {
      default: "var(--pill-bg)",
      ":hover": "var(--bg-elev)",
    },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    color: "var(--fg)",
    paddingTop: "8px",
    paddingRight: "10px",
    paddingBottom: "8px",
    paddingLeft: "10px",
    borderRadius: "var(--radius)",
    cursor: "pointer",
    alignItems: "center",
    justifyContent: "center",
  },
  mpi_pills: {
    WebkitTouchCallout: { default: null, '@media (display-mode: standalone), (display-mode: fullscreen), (display-mode: minimal-ui)': 'none' },
    display: "flex",
    alignItems: "center",
    gap: "8px",
    paddingTop: 0,
    paddingRight: {
      default: "16px",
      "@media (max-width: 900px)": "max(12px, env(safe-area-inset-right))",
    },
    paddingBottom: "10px",
    paddingLeft: {
      default: "16px",
      "@media (max-width: 900px)": "max(12px, env(safe-area-inset-left))",
    },
    flexWrap: "wrap",
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    paddingTop: {
      default: "6px",
      "@media (max-width: 480px)": "5px",
    },
    paddingRight: {
      default: "12px",
      "@media (max-width: 480px)": "10px",
    },
    paddingBottom: {
      default: "6px",
      "@media (max-width: 480px)": "5px",
    },
    paddingLeft: {
      default: "12px",
      "@media (max-width: 480px)": "10px",
    },
    backgroundColor: "var(--pill-bg)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    color: "var(--fg)",
    borderRadius: "999px",
    fontSize: {
      default: "0.85rem",
      "@media (max-width: 480px)": "0.78rem",
    },
    cursor: "default",
    whiteSpace: "nowrap",
  },
  pill_clickable: {
    cursor: "pointer",
    backgroundColor: {
      default: "var(--pill-bg)",
      ":hover": "var(--bg-elev)",
    },
  },
  pill_label: {
    color: "var(--muted)",
    fontSize: {
      default: "0.75rem",
      "@media (max-width: 480px)": "0.68rem",
    },
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  acct_dropdown: {
    position: "relative",
  },
  acct_chevron: {
    display: "inline-flex",
    transition: "transform 0.2s ease",
    transform: "rotate(-90deg)",
  },
  acct_chevron_open: {
    transform: "rotate(0deg)",
  },
  acct_dropdown_menu: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    minWidth: "260px",
    maxWidth: "calc(100vw - 32px)",
    backgroundColor: "var(--card)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius)",
    boxShadow: "var(--shadow)",
    zIndex: 80,
    overflow: "hidden",
    transformOrigin: "top left",
    animationName: dropdown_in,
    animationDuration: '100ms',
    animationTimingFunction: 'ease-out',
    animationFillMode: 'forwards',
  },
  acct_dropdown_closing: {
    animationName: dropdown_out,
    animationDuration: '80ms',
    animationTimingFunction: 'ease-in',
    animationFillMode: 'forwards',
  },
  acct_list: {
    display: "flex",
    flexDirection: "column",
  },
  acct_item: {
    display: "flex",
    alignItems: "center",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    width: "100%",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--bg-elev)",
    },
    color: "var(--fg)",
    borderWidth: 0,
    borderStyle: "none",
    borderBottomWidth: {
      default: "1px",
      ":last-child": 0,
    },
    borderBottomStyle: {
      default: "solid",
      ":last-child": "none",
    },
    borderBottomColor: "var(--border)",
    fontSize: "0.9rem",
  },
  acct_item_active: {
    backgroundColor: {
      default: "color-mix(in srgb, var(--brand) 6%, transparent)",
      ":hover": "color-mix(in srgb, var(--brand) 6%, transparent)",
    },
  },
  acct_switch_btn: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    paddingTop: "10px",
    paddingRight: "12px",
    paddingBottom: "10px",
    paddingLeft: "12px",
    backgroundColor: "transparent !important",
    borderWidth: 0,
    borderStyle: "none",
    color: "inherit !important",
    cursor: "pointer",
    textAlign: "left",
    minWidth: 0,
    fontWeight: "inherit",
    justifyContent: "flex-start",
  },
  acct_info: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  acct_name: {
    fontSize: "0.88rem",
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: 1.2,
  },
  acct_handle: {
    color: "var(--muted)",
    fontWeight: 400,
    fontSize: "0.9em",
  },
  acct_meta: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    flexWrap: "wrap",
  },
  acct_badge: {
    fontSize: "0.68rem",
    paddingTop: "1px",
    paddingRight: "5px",
    paddingBottom: "1px",
    paddingLeft: "5px",
    borderRadius: "4px",
    backgroundColor: "var(--bg-elev)",
    color: "var(--muted)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    lineHeight: 1.4,
  },
  acct_badge_staging: {
    backgroundColor: "color-mix(in srgb, #b45309 12%, transparent)",
    color: "#92400e",
    borderColor: "color-mix(in srgb, #b45309 30%, transparent)",
  },
  acct_balance: {
    fontSize: "0.73rem",
    color: "var(--muted)",
  },
  acct_remove: {
    flexShrink: 0,
    color: {
      default: "var(--muted) !important",
      ":hover": "var(--alert-error) !important",
    },
    backgroundColor: "transparent !important",
    borderWidth: 0,
    borderStyle: "none",
    paddingTop: "10px",
    paddingRight: "10px",
    paddingBottom: "10px",
    paddingLeft: "10px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  acct_remove_active: {
    color: "var(--brand) !important",
    fontSize: "0.85rem",
    fontWeight: 700,
  },
  acct_footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    paddingTop: "8px",
    paddingRight: "12px",
    paddingBottom: "8px",
    paddingLeft: "12px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
  },
  acct_add_btn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "0.85rem",
    color: "var(--brand) !important",
    backgroundColor: {
      default: "transparent !important",
      ":hover": "transparent !important",
    },
    borderWidth: 0,
    borderStyle: "none",
    cursor: "pointer",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    fontWeight: 500,
    textDecoration: {
      default: null,
      ":hover": "underline",
    },
  },
  pill_balance_value: {
    fontWeight: 600,
    color: 'var(--brand)',
  },
  pill_profile_badge: {
    paddingTop: 2,
    paddingRight: 8,
    paddingBottom: 2,
    paddingLeft: 8,
    borderColor: 'color-mix(in srgb, #8b5cf6 30%, var(--border))',
    borderRadius: 6,
    backgroundColor: 'color-mix(in srgb, #8b5cf6 14%, var(--card))',
    color: 'color-mix(in srgb, #8b5cf6 60%, var(--fg))',
    fontSize: '0.75rem',
    fontWeight: 600,
    whiteSpace: 'normal',
    overflowWrap: 'anywhere',
  },
  acct_icon_visible: {
    display: 'flex',
    alignItems: 'center',
  },
  acct_icon_hidden: {
    display: 'none',
  },
});

export const shell_classes = {
  mpi_shell: stylex.props(styles.mpi_shell).className,
  mpi_shell_settings: stylex.props(styles.mpi_shell, styles.mpi_shell_settings).className,
  mpi_sticky_top: stylex.props(styles.mpi_sticky_top).className,
  mpi_header: stylex.props(styles.mpi_header).className,
  verification_banner_stack: stylex.props(styles.verification_banner_stack).className,
  mpi_header_row: stylex.props(styles.mpi_header_row).className,
  mpi_header_logo: stylex.props(styles.mpi_header_logo).className,
  mpi_header_spacer: stylex.props(styles.mpi_header_spacer).className,
  hamburger_btn: stylex.props(styles.hamburger_btn).className,
  mpi_pills: stylex.props(styles.mpi_pills).className,
  pill: stylex.props(styles.pill).className,
  pill_clickable: stylex.props(styles.pill, styles.pill_clickable).className,
  pill_label: stylex.props(styles.pill_label).className,
  acct_dropdown: stylex.props(styles.acct_dropdown).className,
  acct_chevron: stylex.props(styles.acct_chevron).className,
  acct_chevron_open: stylex.props(styles.acct_chevron, styles.acct_chevron_open).className,
  acct_dropdown_menu: stylex.props(styles.acct_dropdown_menu).className,
  acct_dropdown_closing: stylex.props(styles.acct_dropdown_menu, styles.acct_dropdown_closing).className,
  acct_list: stylex.props(styles.acct_list).className,
  acct_item: stylex.props(styles.acct_item).className,
  acct_item_active: stylex.props(styles.acct_item, styles.acct_item_active).className,
  acct_switch_btn: stylex.props(styles.acct_switch_btn).className,
  acct_info: stylex.props(styles.acct_info).className,
  acct_name: stylex.props(styles.acct_name).className,
  acct_handle: stylex.props(styles.acct_handle).className,
  acct_meta: stylex.props(styles.acct_meta).className,
  acct_badge: stylex.props(styles.acct_badge).className,
  acct_badge_staging: stylex.props(styles.acct_badge, styles.acct_badge_staging).className,
  acct_balance: stylex.props(styles.acct_balance).className,
  acct_remove: stylex.props(styles.acct_remove).className,
  acct_remove_active: stylex.props(styles.acct_remove, styles.acct_remove_active).className,
  acct_footer: stylex.props(styles.acct_footer).className,
  acct_add_btn: stylex.props(styles.acct_add_btn).className,
  pill_balance_value: stylex.props(styles.pill_balance_value).className,
  pill_profile_badge: stylex.props(styles.pill, styles.pill_profile_badge).className,
  acct_icon_visible: stylex.props(styles.acct_icon_visible).className,
  acct_icon_hidden: stylex.props(styles.acct_icon_hidden).className,
};
