import * as stylex from '@stylexjs/stylex';

const panel_in = stylex.keyframes({
  from: { transform: 'translateX(100%)' },
  to: { transform: 'translateX(0)' },
});

const panel_out = stylex.keyframes({
  from: { transform: 'translateX(0)' },
  to: { transform: 'translateX(100%)' },
});

const styles = stylex.create({
  tp: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    zIndex: 160,
    width: "var(--mpi-tp-w)",
    maxWidth: "100vw",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "var(--bg-elev)",
    borderLeftWidth: {
      default: "1px",
      "@media (max-width: 620px)": 0,
    },
    borderLeftStyle: {
      default: "solid",
      "@media (max-width: 620px)": "none",
    },
    borderLeftColor: "var(--border)",
    boxShadow: {
      default: null,
      "@media (max-width: 620px)": "-14px 0 34px rgba(0, 0, 0, 0.3)",
    },
    animationName: panel_in,
    animationDuration: '260ms',
    animationTimingFunction: 'cubic-bezier(0.32, 0.72, 0, 1)',
  },
  tp__closing: {
    pointerEvents: "none",
    animationName: panel_out,
    animationFillMode: 'forwards',
  },
  tp_head: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    height: "56px",
    flexShrink: 0,
    paddingTop: 0,
    paddingRight: "10px",
    paddingBottom: 0,
    paddingLeft: "18px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
  },
  tp_head_title: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minWidth: 0,
    fontSize: "1.02rem",
    fontWeight: 700,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  tp_icon_btn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in srgb, var(--fg) 10%, transparent)",
    },
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "999px",
    color: {
      default: "var(--muted)",
      ":hover": "var(--fg)",
    },
    cursor: "pointer",
    flexShrink: 0,
    transition: "color 0.12s, background 0.12s",
  },
  tp_progress: {
    display: "flex",
    gap: "4px",
    paddingTop: "10px",
    paddingRight: "12px",
    paddingBottom: "10px",
    paddingLeft: "12px",
    flexShrink: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
  },
  tp_step: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "7px",
    paddingTop: "7px",
    paddingRight: "8px",
    paddingBottom: "7px",
    paddingLeft: "8px",
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in srgb, var(--fg) 7%, transparent)",
    },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "8px",
    color: {
      default: "var(--muted)",
      ":hover": "var(--fg)",
    },
    fontSize: "0.76rem",
    fontWeight: 500,
  },
  tp_step_is_on: {
    backgroundColor: {
      default: "var(--card)",
      ":hover": "var(--card)",
    },
    borderColor: "var(--border)",
    color: {
      default: "var(--fg)",
      ":hover": "var(--fg)",
    },
  },
  tp_step_num: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "18px",
    height: "18px",
    flexShrink: 0,
    borderRadius: "50%",
    backgroundColor: "var(--pill-bg)",
    color: "var(--muted)",
    fontSize: "0.68rem",
    fontWeight: 700,
  },
  tp_step_text: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tp_share: {
    flexShrink: 0,
    paddingTop: "10px",
    paddingRight: "14px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
  },
  tp_preview: {
    flexShrink: 0,
    paddingTop: "14px",
    paddingRight: "16px",
    paddingBottom: "14px",
    paddingLeft: "16px",
    backgroundColor: "var(--bg)",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
  },
  tp_preview_card: {
    backgroundColor: "var(--card)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "var(--radius)",
    boxShadow: "var(--shadow)",
    paddingTop: "12px",
    paddingRight: "14px",
    paddingBottom: "12px",
    paddingLeft: "14px",
  },
  tp_preview_title: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: "10px",
    marginLeft: 0,
    fontSize: "1.05rem",
    fontWeight: 700,
    color: "var(--fg)",
  },
  tp_preview_rows: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBottom: "11px",
  },
  tp_preview_bar: {
    height: "7px",
    width: "58%",
    borderRadius: "4px",
    backgroundColor: "var(--fg)",
  },
  tp_preview_bar__muted: {
    width: "82%",
    height: "6px",
    backgroundColor: "var(--muted)",
  },
  tp_preview_controls: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
  },
  tp_preview_btn: {
    paddingTop: "4px",
    paddingRight: "11px",
    paddingBottom: "4px",
    paddingLeft: "11px",
    borderRadius: "7px",
    backgroundColor: "var(--brand)",
    color: "var(--brand-text)",
    fontSize: "0.72rem",
    fontWeight: 600,
  },
  tp_preview_pill: {
    paddingTop: "4px",
    paddingRight: "10px",
    paddingBottom: "4px",
    paddingLeft: "10px",
    borderRadius: "999px",
    backgroundColor: "var(--pill-bg)",
    color: "var(--fg)",
    fontSize: "0.72rem",
  },
  tp_preview_dot: {
    width: "9px",
    height: "9px",
    borderRadius: "50%",
    flexShrink: 0,
  },
  tp_body: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minHeight: 0,
    overflowY: "auto",
    paddingTop: "16px",
    paddingRight: "18px",
    paddingBottom: "22px",
    paddingLeft: "18px",
  },
  tp_h: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    fontSize: "1rem",
    fontWeight: 700,
  },
  tp_hint: {
    marginTop: "4px",
    marginRight: 0,
    marginBottom: "14px",
    marginLeft: 0,
    fontSize: "0.82rem",
    color: "var(--muted)",
    lineHeight: 1.5,
  },
  tp_label: {
    marginTop: "18px",
    marginRight: 0,
    marginBottom: "7px",
    marginLeft: 0,
    fontSize: "0.78rem",
    color: "var(--muted)",
  },
  tp_inline: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  tp_swatches: {
    display: "flex",
    flexWrap: "wrap",
    gap: "7px",
  },
  tp_swatch: {
    width: "28px",
    height: "28px",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    borderRadius: "8px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    cursor: "pointer",
    transition: "transform 0.1s ease, box-shadow 0.12s ease",
    transform: {
      default: null,
      ":hover": "translateY(-2px)",
    },
  },
  tp_swatch_is_on: {
    boxShadow: "0 0 0 2px var(--bg-elev), 0 0 0 4px var(--fg)",
  },
  tp_seg: {
    display: "flex",
    gap: "4px",
    paddingTop: "3px",
    paddingRight: "3px",
    paddingBottom: "3px",
    paddingLeft: "3px",
    backgroundColor: "var(--bg)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: "10px",
  },
  tp_tiles: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: {
      default: "8px",
      "@media (max-width: 620px)": "6px",
    },
    marginTop: "12px",
  },
  tp_tile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: "7px",
    paddingTop: "8px",
    paddingRight: "8px",
    paddingBottom: "8px",
    paddingLeft: "8px",
    backgroundColor: {
      default: "var(--card)",
      ":hover": "var(--card)",
    },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: "var(--border)",
      ":hover": "var(--muted)",
    },
    borderRadius: "10px",
    color: {
      default: "var(--fg)",
      ":hover": "var(--fg)",
    },
  },
  tp_tile_is_on: {
    borderColor: {
      default: "var(--brand)",
      ":hover": "var(--brand)",
    },
    boxShadow: "0 0 0 1px var(--brand)",
  },
  tp_tile_art: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    gap: "4px",
    height: "42px",
    paddingTop: "6px",
    paddingRight: "6px",
    paddingBottom: "6px",
    paddingLeft: "6px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderRadius: "6px",
  },
  tp_tile_label: {
    fontSize: "0.78rem",
    fontWeight: 500,
  },
  tp_slider_head: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "18px",
    marginRight: 0,
    marginBottom: "8px",
    marginLeft: 0,
    fontSize: "0.78rem",
    color: "var(--muted)",
  },
  tp_range: {
    width: "100%",
    accentColor: "var(--brand)",
    cursor: "pointer",
  },
  tp_vars: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  tp_var: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  tp_var_name: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    minWidth: 0,
    fontSize: "0.82rem",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  tp_foot: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    flexShrink: 0,
    paddingTop: "12px",
    paddingRight: "16px",
    paddingBottom: "calc(12px + env(safe-area-inset-bottom))",
    paddingLeft: "16px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    backgroundColor: "var(--bg-elev)",
  },
  tp_foot_actions: {
    display: "flex",
    gap: "8px",
  },
  tp_chev_back: {
    display: "flex",
    transform: "rotate(180deg)",
  },
  tp_text_btn: {
    paddingTop: "6px",
    paddingRight: "2px",
    paddingBottom: "6px",
    paddingLeft: "2px",
    backgroundColor: {
      default: "transparent",
      ":hover": "transparent",
      ":disabled": "transparent !important",
    },
    borderWidth: 0,
    borderStyle: "none",
    color: {
      default: "var(--muted)",
      ":hover": "var(--fg)",
      ":disabled": "var(--muted) !important",
      ":disabled:hover": "var(--muted) !important",
    },
    fontSize: "0.82rem",
    opacity: {
      default: null,
      ":disabled": 0.4,
    },
  },
  tp_legacy_toggle: {
    width: "100%",
    justifyContent: "space-between",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--bg-elev)",
    },
    color: {
      default: "var(--fg)",
      ":hover": "var(--fg)",
    },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--border)",
    paddingTop: "11px",
    paddingRight: "14px",
    paddingBottom: "11px",
    paddingLeft: "14px",
    fontSize: "0.9rem",
  },
  tp_legacy_toggle_chevron: {
    display: "flex",
    color: "var(--muted)",
    transition: "transform 0.16s ease",
  },
  tp_legacy_body: {
    paddingTop: "4px",
    paddingRight: "2px",
    paddingBottom: "8px",
    paddingLeft: "2px",
  },
  tp_step_num_on: {
    backgroundColor: 'var(--brand)',
    color: 'var(--brand-text)',
  },
  tp_step_num_done: {
    backgroundColor: 'color-mix(in srgb, var(--brand) 40%, transparent)',
    color: 'var(--fg)',
  },
  tp_share_row: {
    margin: 0,
    gap: 6,
    flexWrap: 'nowrap',
  },
  tp_share_button: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
    minWidth: 0,
    paddingTop: 6,
    paddingRight: 4,
    paddingBottom: 6,
    paddingLeft: 4,
    whiteSpace: 'nowrap',
  },
  tp_inline_text: {
    minWidth: 0,
    fontSize: '0.88rem',
    paddingTop: 8,
    paddingRight: 11,
    paddingBottom: 8,
    paddingLeft: 11,
  },
  tp_inline_color: {
    flexShrink: 0,
  },
  tp_inline_button: {
    flexShrink: 0,
  },
  tp_seg_button: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
    minWidth: 0,
    paddingTop: 7,
    paddingRight: 8,
    paddingBottom: 7,
    paddingLeft: 8,
    backgroundColor: {
      default: 'transparent',
      ':hover': 'color-mix(in srgb, var(--fg) 8%, transparent)',
    },
    color: {
      default: 'var(--muted)',
      ':hover': 'var(--fg)',
    },
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: 7,
    fontSize: '0.82rem',
    fontWeight: 500,
  },
  tp_seg_button_on: {
    backgroundColor: {
      default: 'var(--brand)',
      ':hover': 'var(--brand)',
    },
    color: {
      default: 'var(--brand-text)',
      ':hover': 'var(--brand-text)',
    },
  },
  tp_tile_art_span: {
    height: 6,
    borderRadius: 3,
  },
  tp_tile_art_span_last: {
    width: '46%',
  },
  tp_var_color: {
    width: 34,
    height: 30,
    flexShrink: 0,
    paddingTop: 2,
    paddingRight: 2,
    paddingBottom: 2,
    paddingLeft: 2,
  },
  tp_var_hex: {
    width: {
      default: 84,
      '@media (max-width: 620px)': 78,
    },
    flexShrink: 0,
    fontSize: '0.8rem',
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 6,
    paddingLeft: 8,
  },
  tp_legacy_toggle_chevron_expanded: {
    transform: 'rotate(90deg)',
  },
});

export const theme_panel_classes = {
  tp: stylex.props(styles.tp).className,
  tp__closing: stylex.props(styles.tp, styles.tp__closing).className,
  tp_head: stylex.props(styles.tp_head).className,
  tp_head_title: stylex.props(styles.tp_head_title).className,
  tp_icon_btn: stylex.props(styles.tp_icon_btn).className,
  tp_progress: stylex.props(styles.tp_progress).className,
  tp_step: stylex.props(styles.tp_step).className,
  tp_step_is_on: stylex.props(styles.tp_step, styles.tp_step_is_on).className,
  tp_step_num: stylex.props(styles.tp_step_num).className,
  tp_step_num_on: stylex.props(styles.tp_step_num, styles.tp_step_num_on).className,
  tp_step_num_done: stylex.props(styles.tp_step_num, styles.tp_step_num_done).className,
  tp_step_text: stylex.props(styles.tp_step_text).className,
  tp_share: stylex.props(styles.tp_share).className,
  tp_share_row: stylex.props(styles.tp_share_row).className,
  tp_share_button: stylex.props(styles.tp_share_button).className,
  tp_preview: stylex.props(styles.tp_preview).className,
  tp_preview_card: stylex.props(styles.tp_preview_card).className,
  tp_preview_title: stylex.props(styles.tp_preview_title).className,
  tp_preview_rows: stylex.props(styles.tp_preview_rows).className,
  tp_preview_bar: stylex.props(styles.tp_preview_bar).className,
  tp_preview_bar__muted: stylex.props(styles.tp_preview_bar, styles.tp_preview_bar__muted).className,
  tp_preview_controls: stylex.props(styles.tp_preview_controls).className,
  tp_preview_btn: stylex.props(styles.tp_preview_btn).className,
  tp_preview_pill: stylex.props(styles.tp_preview_pill).className,
  tp_preview_dot: stylex.props(styles.tp_preview_dot).className,
  tp_body: stylex.props(styles.tp_body).className,
  tp_h: stylex.props(styles.tp_h).className,
  tp_hint: stylex.props(styles.tp_hint).className,
  tp_label: stylex.props(styles.tp_label).className,
  tp_inline: stylex.props(styles.tp_inline).className,
  tp_inline_text: stylex.props(styles.tp_inline_text).className,
  tp_inline_color: stylex.props(styles.tp_inline_color).className,
  tp_inline_button: stylex.props(styles.tp_inline_button).className,
  tp_swatches: stylex.props(styles.tp_swatches).className,
  tp_swatch: stylex.props(styles.tp_swatch).className,
  tp_swatch_is_on: stylex.props(styles.tp_swatch, styles.tp_swatch_is_on).className,
  tp_seg: stylex.props(styles.tp_seg).className,
  tp_seg_button: stylex.props(styles.tp_seg_button).className,
  tp_seg_button_on: stylex.props(styles.tp_seg_button, styles.tp_seg_button_on).className,
  tp_tiles: stylex.props(styles.tp_tiles).className,
  tp_tile: stylex.props(styles.tp_tile).className,
  tp_tile_is_on: stylex.props(styles.tp_tile, styles.tp_tile_is_on).className,
  tp_tile_art: stylex.props(styles.tp_tile_art).className,
  tp_tile_art_span: stylex.props(styles.tp_tile_art_span).className,
  tp_tile_art_span_last: stylex.props(styles.tp_tile_art_span, styles.tp_tile_art_span_last).className,
  tp_tile_label: stylex.props(styles.tp_tile_label).className,
  tp_slider_head: stylex.props(styles.tp_slider_head).className,
  tp_range: stylex.props(styles.tp_range).className,
  tp_vars: stylex.props(styles.tp_vars).className,
  tp_var: stylex.props(styles.tp_var).className,
  tp_var_name: stylex.props(styles.tp_var_name).className,
  tp_var_color: stylex.props(styles.tp_var_color).className,
  tp_var_hex: stylex.props(styles.tp_var_hex).className,
  tp_foot: stylex.props(styles.tp_foot).className,
  tp_foot_actions: stylex.props(styles.tp_foot_actions).className,
  tp_chev_back: stylex.props(styles.tp_chev_back).className,
  tp_text_btn: stylex.props(styles.tp_text_btn).className,
  tp_legacy_toggle: stylex.props(styles.tp_legacy_toggle).className,
  tp_legacy_toggle_chevron: stylex.props(styles.tp_legacy_toggle_chevron).className,
  tp_legacy_toggle_chevron_expanded: stylex.props(styles.tp_legacy_toggle_chevron, styles.tp_legacy_toggle_chevron_expanded).className,
  tp_legacy_body: stylex.props(styles.tp_legacy_body).className,
};
